### PR TITLE
fix: Rule to match entire body (When body is not an object) 

### PR DESCRIPTION
**Pull request by bykof**
Parent issue

Closes #mockoon/mockoon#271

Technical implementation details

Nothing really complicated

### CODE REVIEW

**Comment by bykof** [comment]
Let me test the code first before we merge this PR :)

**Comment by bykof** [comment]
Ok I tested it, now it works :)

**Comment by bykof** [comment]
Hi @255kb I just wanted to leave you a message here, that the former pull request wasnt tested properly, I tested it and I found this bug. 
Feel free to check it but this should go together with https://github.com/mockoon/commons/pull/14

**Review by 255kb — APPROVED** [review]

**Comment by 255kb** [comment]
@bykof Indeed, forgot about this check. It should be on NPM v1.1.2 now.

**Comment by bykof** [comment]
@255kb thank you very much for this fast response! Can you tell me, when do you plan to release mockoon? :)

**Comment by 255kb** [comment]
@bykof I cannot give any precise ETA, I would like to try to publish something around beginning of February. I still have one PR to review, and I'm in the middle of migrating to Angular 9+ (not sure I can finish this for this release). We also have one feature under development that I would like to include.

Do you plan to open a PR in the main app for this mockoon/mockoon#271 (bumping lib version + adding automated tests)?

**Comment by bykof** [comment]
> Do you plan to open a PR in the main app for this [mockoon/mockoon#271](https://github.com/mockoon/mockoon/issues/271) (bumping lib version + adding automated tests)?

Yeah I can do it. 

Thank you for your answer, just wanted to know if you plan a new release in 6 months or rather next month :P

**Comment by 255kb** [comment]
If you don't have time for updating the main app I can do it this evening. No issue. I am also very used to writing the tests, so it won't take long.

**Pull request merged**
